# Generated by Django 2.0.13 on 2020-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverid',
            name='num_connected',
            field=models.IntegerField(default=0),
        ),
    ]
